# Generated by Django 4.2.8 on 2023-12-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("surname", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=128)),
                ("verificada", models.BooleanField(default=False)),
            ],
        ),
    ]
