# Generated by Django 4.2.8 on 2023-12-18 17:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="token",
            new_name="key",
        ),
    ]
