# Generated by Django 4.2.8 on 2023-12-19 01:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_rename_verificada_user_is_checked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_checked",
        ),
    ]
