# Generated by Django 4.2.8 on 2023-12-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_user_is_checked"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mail_is_checked",
            field=models.BooleanField(default=False),
        ),
    ]
