# Generated by Django 4.2.8 on 2023-12-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_user_mail_is_checked"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="grupo",
            field=models.CharField(
                choices=[
                    ["1", "cliente"],
                    ["2", "profesional"],
                    ["3", "administrador"],
                ],
                default=1,
                max_length=1,
            ),
        ),
    ]
