# Generated by Django 4.2.8 on 2023-12-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_user_grupo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="grupo",
            field=models.SmallIntegerField(
                choices=[[1, "cliente"], [2, "profesional"], [3, "administrador"]],
                default=1,
            ),
        ),
    ]
