# Generated by Django 4.2.8 on 2023-12-26 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0010_alter_user_grupo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "state",
                    models.SmallIntegerField(
                        choices=[[1, "enabled"], [2, "disabled"]], default=1
                    ),
                ),
                ("appointment_duration", models.SmallIntegerField()),
                (
                    "profesional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="schedules",
                        to="accounts.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
                ("duration", models.PositiveSmallIntegerField()),
                (
                    "state",
                    models.SmallIntegerField(
                        choices=[[1, "free"], [2, "busy"]], default=1
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="appointments",
                        to="schedule.schedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="appointments",
                        to="accounts.user",
                    ),
                ),
            ],
        ),
    ]
